# -*- coding: utf-8 -*-
"""Assignment 01_21101004_AdityaBarua.ipnyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-OP13Y9jtD-9yLTBORIFEAcw4cGQ87-T
"""

#String task-1
var = input("enter a string:")
upper = 0
lower = 0
for i in range(0,len(var)):
    if var[i] >= 'a' and var[i] <= 'z':
        lower += 1
    elif var[i] >= 'A' and var[i] <= 'Z':
        upper += 1
if upper > lower :
    print(var.upper())
else:
    print(var.lower())

#String task-2
var = input('Enter a string:')
count_integer = 0
count_alphabet = 0
count_mixed = 0
for i in var: 
  ord_var = ord(i)
  if (ord_var>=65 and ord_var<=90) or (ord_var>=97 and ord_var<=122) :
    count_alphabet += 1
  elif ord_var>=48 and ord_var<=57:
    count_integer += 1
if count_integer > 0 and count_alphabet > 0:
  print('MIXED')
elif count_integer > 0:
  print('NUMBER')
else:
  print('WORD')

#String task-3
str1 = input()
start = 0
end = 0
for i in range(len(str1)):
    if ord(str1[i]) >= 65 and ord(str1[i]) <= 90 :
        start = i
        break
for i in range(start+1,len(str1)):
    if ord(str1[i]) >= 65 and ord(str1[i]) <= 90:
        end = i
        break
if start+1 == end:
    print("BLANK")
else:
    print(str1[start+1:end])

#String task -4
list1 = []
diff = []
final = []
match = []
count = 1
while count == 1:
    var = input("enter:").upper()
    if var != "STOP":
        list1 = var.split()
        for i in range(len(list1)):
            list1[i] = int (list1[i])
            match.append(i)
        for i in range(len(list1)-1):
            diff.append(list1[i] - list1[i+1])
        for i in diff:
            if i < 0:
                i = i * (-1)
                final.append(i)
            else:
                final.append(i)
        match = match[1::]
        final.sort()
        if final == match:
            print("UB jumper")
        else:
            print("Not UB jumper")
    else:
        count = 0

#String task-5
var_1 = input('enter a string:')
var_2 = input('enter another string:')
count = 0
str1= ""
for i in var_1:
    for j in var_2:
        if i == j:
            count += 1
if count == 0:
    print("Nothing in common.")
else:
        var_3 = [s for s in var_1 if s in var_2]
        var_4 = [s for s in var_2 if s in var_1]
        result = var_3 + var_4
        for i in result:
            str1 = str1 + i
print(str1)

#String task-6
str1 = input()
uppercase_count = 0 
lowercase_count = 0
digit_count = 0
special_count = 0
special_char = '_$#@'
for i in str1:
    if ord(i)>= 65 and ord(i) <= 90:
        uppercase_count += 1
    elif ord(i) >= 97 and ord(i) <= 122:
        lowercase_count += 1
    elif ord(i) >= 48 and ord(i) <= 57:
        digit_count += 1
    elif i in special_char:
        special_count += 1
if uppercase_count>0 and lowercase_count>0 and digit_count>0 and special_count>0:
    print("OK")
if uppercase_count == 0:
    print("Uppercase character missing",end=",")
if lowercase_count == 0:
    print("Lowercase character missing",end=",")
if digit_count == 0:
    print("Digit missing",end=",")
if special_count == 0:
    print("Special character missing")

#List task-1
names = []
new_name = ''

while new_name != 'STOP':
    new_name = input("Enter numbers:").upper()
    if new_name == 'STOP':
        break
    else:
        names.append(new_name)

for item in names:
    print(item,"-",names.count(item),"times")

#List task-2
highest_sum = 0
for i in range(int(input('enter a range:'))): 
    list1 = [int(i) for i in input().split()]
    total = 0
    for j in range(len(list1)):
        total = total + list1[j]
    if total > highest_sum:
        highest_sum = total
        highest_list = list1
print(highest_sum)
print(highest_list)

#List task-3
list1 = [int(i) for i in input().split()]
list2 = [int(j) for j in input().split()]
total = 0
my_list= []
for i in range(len(list1)):
    for j in range(len(list2)):
        total =list1[i]*list2[j]
        my_list.append(total)
print(my_list)

#List task - 4
var = input("enter a string:")
str1 = "too good"
str2 = "excellent"
var1 = var.find(str1)
var2 = var1 + len(str1)
if str1 not in var:
    print(var)
else:
    replaced_str = var[:var1] + str2 + var[var2:]
    print(replaced_str)

#List task - 5
s = input()
l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
l6 = []
for i in s:
    l1.append(i)
for j in l1:
    if ord(j) >= 97 and ord(j) <= 122:
        l2.append(j)
l2.sort()
for k in l1:
    if ord(k) >= 65 and ord(k) <= 90:
        l3.append(k)
l3.sort()
for m in l1:
    if ord(m) >= 48 and ord(m) <= 57:
        l4.append(m)
l4.sort()
for x in l4:
    if int(x)%2!=0:
        l5.append(x)
    elif int(x)%2== 0:
        l6.append(x)
l5.sort()
l6.sort()
result = l2+l3+l5+l6
for i in result:
    print(i,end = "")

#List task - 6
list1 = [int(i) for i in input("number of participants & heads rule :").split()]
list2 = []
count = 0
num = list1[0]
for i in range(num):
    x = int(input("participation time:"))
    list2.append(x)
#print(list2)
y = list1[0]
z = list1[1]
for j in list2 :
    if 5-j >= z:
        count += 1
result = count // 3
print(result)



#Dictionary & Tuple task-1
n1 = int(input('enter a range:'))
dict1 = {}
dict2 = {}
for i in range(n1):
	key = input("Enter key for dict1:")
	value = int(input("Enter value for dict1:"))
	dict1[key] = value
print("Dict1",dict1)
n2 = int(input('enter a range:'))
for i in range(n2):
	key = input("Enter key for dict2:")
	value = int(input("Enter value for dict2:"))
	dict2[key] = value
print("Dict2:",dict2)
dict3 ={}
for i in dict1:
    dict3[i] = dict1[i]
for i in dict2:
    if i in dict3:
        dict3[i] += dict2[i]
    else:
        dict3[i] = dict2[i]
print("Combination of Dict1 and Dict2",dict3)
list1 = []
for k in dict3:
    if dict3[k] not in list1:
        list1.append(dict3[k])
for i in range(len(list1)):
    for j in range(len(list1)):
        if list1[j] > list1[i]:
            temp = list1[j]
            list1[j] = list1[i]
            list1[i] = temp
list1 = tuple (list1)
print(list1)

#Dictionary & task- 2
dict1 = {}
i = input().upper()
while i != "STOP":
    if int(i) in dict1:
        dict1[int(i)] += 1
    else:
        dict1[int(i)] = 1
    i = input().upper()
for i,j in dict1.items():
    print(i,"has occured",j,"times")

#Dictionary & tuple task -3
n = int(input('enter a range'))
dict1 = {}
for i in range(n):
	key = input("Enter key for dict1:")
	value = input("Enter value for dict1:")
	dict1[key] = value
print("Dict1",dict1)
dict2 = {}
for i,j in dict1.items():
    if j in dict2:
        dict2[j].append(i)
    else:
        dict2[j] = [i]
print(dict2)

#Dictionary & tuple task - 4
str1 = input()
str2 = input()
dict1 = {}
dict2 = {}
for ch in str1:
    if ch in dict1:
        dict1[ch] = dict1[ch]+1
    else:
        dict1[ch] = 1
for ch in str2:
    if ch in dict2:
        dict2[ch] = dict2[ch]+1
    else:
        dict2[ch] = 1
total = 0
for key in dict1:
    if key in dict2:
        if dict1[key] == dict2[key]:
            total += 1
if len(str1) == total and len(str2) == total:
    print("Those strings are anagrams.")
else:
    print("Those strings are not anagrams.")

#Dictionary & tuple task-5
str1 = input()
dict1 = {1:[".",",","?","!",":"],2:["A","B","C"],3:["D","E","F"],4:["G","H","I"],5:["J","K","L"],6:["M","N","O"],7:["P","Q","R","S"],8:["T","U","V"],9:["W","X","Y","Z"],0:[" "]}
result = ""
str2 = ""
for i in range(len(str1)):
    if ord(str1[i]) >= 97 and ord(str1[i]) <= 122:
        str2 = str2 + chr(ord(str1[i])-32 )
    else:
        str2 = str2 + str1[i]
for i in range(len(str2)):
    for j,k in dict1.items():
        if str2[i] in k :
            for l in range(len(k)):
                if str2[i] == k[l]:
                    x = len(k[:l+1])
                    for m in range(x):
                        result += str (j)
print(result)